// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;


namespace GPSCrypto
{

    public partial class Login_JSON
    {

        [JsonProperty("UserName")]
        public string UserName { get; set; }

        [JsonProperty("Mobile")]
        public string Mobile { get; set; }
    }

}
