// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace GPSCrypto
{

    public partial class MessgaeData
    {

        [JsonProperty("mess_id")]
        public string MessId { get; set; }

        [JsonProperty("from_id")]
        public string FromId { get; set; }

        [JsonProperty("to_id")]
        public string ToId { get; set; }

        [JsonProperty("location")]
        public string Location { get; set; }

        [JsonProperty("crypttype")]
        public string Crypttype { get; set; }

        [JsonProperty("message")]
        public string Message { get; set; }
    }

}
